import "server-only";

import type { RecapNarrative, VerifiedRecapPayload } from "@/lib/recap/types";

function escapeHtml(value: string) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}

function signed(value: number) { return `${value > 0 ? "+" : ""}${value}`; }

export function buildSundayRecapEmail(input: { payload: VerifiedRecapPayload; narrative: RecapNarrative; leagueUrl: string }) {
  const { payload, narrative } = input;
  const selectedFacts = narrative.stories.map((story) => ({ story, fact: payload.facts.find((fact) => fact.id === story.factId)! }));
  const subject = `${payload.league.name} Week ${payload.league.week}: ${narrative.subjectHook}`.replaceAll(/[\r\n]+/g, " ").slice(0, 150);
  const standingsText = payload.standings.map((row) => `#${row.position} ${row.poolTeamName ?? row.ownerName} — ${row.totalPoints} (${signed(row.weeklyPoints)} this week)`).join("\n");
  const text = [subject, "", narrative.opening, "", ...selectedFacts.flatMap(({ story, fact }) => [fact.label, fact.text, story.reaction, ""]), "Standings", standingsText, "", narrative.closing, "", `Open league: ${input.leagueUrl}`, "Support: cfbpooltest@gmail.com"].join("\n");
  const storyHtml = selectedFacts.map(({ story, fact }) => `<tr><td style="padding:0 0 18px;"><div style="color:#ea580c;font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">${escapeHtml(fact.label)}</div><div style="margin-top:5px;color:#0f172a;font-size:17px;font-weight:800;line-height:1.5;">${escapeHtml(fact.text)}</div><div style="margin-top:5px;color:#475569;font-size:14px;font-style:italic;line-height:1.5;">${escapeHtml(story.reaction)}</div></td></tr>`).join("");
  const standingsHtml = payload.standings.map((row) => `<tr><td style="padding:9px 4px;border-bottom:1px solid #e2e8f0;color:#0f172a;font-weight:800;">#${row.position} ${escapeHtml(row.poolTeamName ?? row.ownerName)}</td><td align="right" style="padding:9px 4px;border-bottom:1px solid #e2e8f0;color:#0f172a;font-weight:800;">${row.totalPoints}</td><td align="right" style="padding:9px 4px;border-bottom:1px solid #e2e8f0;color:${row.weeklyPoints < 0 ? "#b91c1c" : row.weeklyPoints > 0 ? "#15803d" : "#64748b"};font-size:12px;font-weight:800;">${signed(row.weeklyPoints)}</td></tr>`).join("");
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(subject)}</title></head><body style="margin:0;background:#e2e8f0;color:#0f172a;font-family:Arial,Helvetica,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;">Week ${payload.league.week} around ${escapeHtml(payload.league.name)}.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" style="padding:24px 12px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:620px;background:#fff;border-radius:16px;overflow:hidden;"><tr><td style="background:#061a38;padding:28px 26px;border-bottom:4px solid #f97316;"><div style="color:#fdba74;font-size:11px;font-weight:800;letter-spacing:2px;text-transform:uppercase;">Sunday Recap · ${payload.league.season}</div><div style="margin-top:8px;color:#fff;font-size:29px;font-weight:900;line-height:1.15;">${escapeHtml(payload.league.name)}</div><div style="margin-top:7px;color:#bfdbfe;font-size:16px;font-weight:700;">Week ${payload.league.week} Final</div></td></tr><tr><td style="padding:28px 26px;"><p style="margin:0 0 24px;color:#334155;font-size:16px;line-height:1.65;">${escapeHtml(narrative.opening)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">${storyHtml}</table><div style="margin-top:10px;color:#0b2b59;font-size:20px;font-weight:900;">League Standings</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:8px;font-size:14px;">${standingsHtml}</table><p style="margin:24px 0 0;color:#475569;font-size:15px;line-height:1.6;">${escapeHtml(narrative.closing)}</p><table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" style="margin:26px auto 6px;"><tr><td bgcolor="#f97316" style="border-radius:10px;"><a href="${escapeHtml(input.leagueUrl)}" style="display:inline-block;padding:14px 24px;color:#fff;font-size:15px;font-weight:800;text-decoration:none;">Open League</a></td></tr></table></td></tr><tr><td style="background:#f8fafc;padding:18px 26px;color:#64748b;font-size:12px;line-height:1.6;border-top:1px solid #e2e8f0;">GameHeelTigerNeerRines HQ · Automated facts, sportswriter flavor.<br>Questions or corrections: cfbpooltest@gmail.com</td></tr></table></td></tr></table></body></html>`;
  return { subject, text, html };
}
