-- Repeatable 2026 FBS team catalog (138 programs). Conference affiliations
-- reflect the 2026 football season. Stable abbreviations are used as upsert keys.
-- Existing catalog rows omitted from this authoritative list are retained for
-- historical foreign keys but made unavailable for future draft picks.
begin;

update public.teams set active = false where active;

insert into public.teams (school_name, short_name, abbreviation, conference) values
('Boston College', 'Boston College', 'BC', 'ACC'),
('California', 'California', 'CAL', 'ACC'),
('Clemson', 'Clemson', 'CLEM', 'ACC'),
('Duke', 'Duke', 'DUKE', 'ACC'),
('Florida State', 'Florida State', 'FSU', 'ACC'),
('Georgia Tech', 'Georgia Tech', 'GT', 'ACC'),
('Louisville', 'Louisville', 'LOU', 'ACC'),
('Miami (FL)', 'Miami', 'MIA', 'ACC'),
('NC State', 'NC State', 'NCSU', 'ACC'),
('North Carolina', 'North Carolina', 'UNC', 'ACC'),
('Pittsburgh', 'Pittsburgh', 'PITT', 'ACC'),
('SMU', 'SMU', 'SMU', 'ACC'),
('Stanford', 'Stanford', 'STAN', 'ACC'),
('Syracuse', 'Syracuse', 'SYR', 'ACC'),
('Virginia', 'Virginia', 'UVA', 'ACC'),
('Virginia Tech', 'Virginia Tech', 'VT', 'ACC'),
('Wake Forest', 'Wake Forest', 'WAKE', 'ACC'),
('Army', 'Army', 'ARMY', 'American'),
('Charlotte', 'Charlotte', 'CLT', 'American'),
('East Carolina', 'East Carolina', 'ECU', 'American'),
('Florida Atlantic', 'Florida Atlantic', 'FAU', 'American'),
('Memphis', 'Memphis', 'MEM', 'American'),
('Navy', 'Navy', 'NAVY', 'American'),
('North Texas', 'North Texas', 'UNT', 'American'),
('Rice', 'Rice', 'RICE', 'American'),
('South Florida', 'South Florida', 'USF', 'American'),
('Temple', 'Temple', 'TEM', 'American'),
('Tulane', 'Tulane', 'TULN', 'American'),
('Tulsa', 'Tulsa', 'TLSA', 'American'),
('UAB', 'UAB', 'UAB', 'American'),
('UTSA', 'UTSA', 'UTSA', 'American'),
('Illinois', 'Illinois', 'ILL', 'Big Ten'),
('Indiana', 'Indiana', 'IND', 'Big Ten'),
('Iowa', 'Iowa', 'IOWA', 'Big Ten'),
('Maryland', 'Maryland', 'MD', 'Big Ten'),
('Michigan', 'Michigan', 'MICH', 'Big Ten'),
('Michigan State', 'Michigan State', 'MSU', 'Big Ten'),
('Minnesota', 'Minnesota', 'MINN', 'Big Ten'),
('Nebraska', 'Nebraska', 'NEB', 'Big Ten'),
('Northwestern', 'Northwestern', 'NU', 'Big Ten'),
('Ohio State', 'Ohio State', 'OSU', 'Big Ten'),
('Oregon', 'Oregon', 'ORE', 'Big Ten'),
('Penn State', 'Penn State', 'PSU', 'Big Ten'),
('Purdue', 'Purdue', 'PUR', 'Big Ten'),
('Rutgers', 'Rutgers', 'RUTG', 'Big Ten'),
('UCLA', 'UCLA', 'UCLA', 'Big Ten'),
('USC', 'USC', 'USC', 'Big Ten'),
('Washington', 'Washington', 'WASH', 'Big Ten'),
('Wisconsin', 'Wisconsin', 'WIS', 'Big Ten'),
('Arizona', 'Arizona', 'ARIZ', 'Big 12'),
('Arizona State', 'Arizona State', 'ASU', 'Big 12'),
('Baylor', 'Baylor', 'BAY', 'Big 12'),
('BYU', 'BYU', 'BYU', 'Big 12'),
('Cincinnati', 'Cincinnati', 'CIN', 'Big 12'),
('Colorado', 'Colorado', 'COLO', 'Big 12'),
('Houston', 'Houston', 'HOU', 'Big 12'),
('Iowa State', 'Iowa State', 'ISU', 'Big 12'),
('Kansas', 'Kansas', 'KU', 'Big 12'),
('Kansas State', 'Kansas State', 'KSU', 'Big 12'),
('Oklahoma State', 'Oklahoma State', 'OKST', 'Big 12'),
('TCU', 'TCU', 'TCU', 'Big 12'),
('Texas Tech', 'Texas Tech', 'TTU', 'Big 12'),
('UCF', 'UCF', 'UCF', 'Big 12'),
('Utah', 'Utah', 'UTAH', 'Big 12'),
('West Virginia', 'West Virginia', 'WVU', 'Big 12'),
('Delaware', 'Delaware', 'DEL', 'Conference USA'),
('FIU', 'FIU', 'FIU', 'Conference USA'),
('Jacksonville State', 'Jacksonville State', 'JVST', 'Conference USA'),
('Kennesaw State', 'Kennesaw State', 'KENN', 'Conference USA'),
('Liberty', 'Liberty', 'LIB', 'Conference USA'),
('Middle Tennessee', 'Middle Tennessee', 'MTSU', 'Conference USA'),
('Missouri State', 'Missouri State', 'MOST', 'Conference USA'),
('New Mexico State', 'New Mexico State', 'NMSU', 'Conference USA'),
('Sam Houston', 'Sam Houston', 'SHSU', 'Conference USA'),
('Western Kentucky', 'Western Kentucky', 'WKU', 'Conference USA'),
('Akron', 'Akron', 'AKR', 'MAC'),
('Ball State', 'Ball State', 'BALL', 'MAC'),
('Bowling Green', 'Bowling Green', 'BGSU', 'MAC'),
('Buffalo', 'Buffalo', 'BUFF', 'MAC'),
('Central Michigan', 'Central Michigan', 'CMU', 'MAC'),
('Eastern Michigan', 'Eastern Michigan', 'EMU', 'MAC'),
('Kent State', 'Kent State', 'KENT', 'MAC'),
('Miami (OH)', 'Miami (OH)', 'M-OH', 'MAC'),
('Ohio', 'Ohio', 'OHIO', 'MAC'),
('Sacramento State', 'Sacramento State', 'SAC', 'MAC'),
('Toledo', 'Toledo', 'TOL', 'MAC'),
('UMass', 'UMass', 'MASS', 'MAC'),
('Western Michigan', 'Western Michigan', 'WMU', 'MAC'),
('Air Force', 'Air Force', 'AFA', 'Mountain West'),
('Hawaii', 'Hawaii', 'HAW', 'Mountain West'),
('Nevada', 'Nevada', 'NEV', 'Mountain West'),
('New Mexico', 'New Mexico', 'UNM', 'Mountain West'),
('North Dakota State', 'North Dakota State', 'NDSU', 'Mountain West'),
('Northern Illinois', 'Northern Illinois', 'NIU', 'Mountain West'),
('San Jose State', 'San Jose State', 'SJSU', 'Mountain West'),
('UNLV', 'UNLV', 'UNLV', 'Mountain West'),
('UTEP', 'UTEP', 'UTEP', 'Mountain West'),
('Wyoming', 'Wyoming', 'WYO', 'Mountain West'),
('Boise State', 'Boise State', 'BOIS', 'Pac-12'),
('Colorado State', 'Colorado State', 'CSU', 'Pac-12'),
('Fresno State', 'Fresno State', 'FRES', 'Pac-12'),
('Oregon State', 'Oregon State', 'ORST', 'Pac-12'),
('San Diego State', 'San Diego State', 'SDSU', 'Pac-12'),
('Texas State', 'Texas State', 'TXST', 'Pac-12'),
('Utah State', 'Utah State', 'USU', 'Pac-12'),
('Washington State', 'Washington State', 'WSU', 'Pac-12'),
('Alabama', 'Alabama', 'ALA', 'SEC'),
('Arkansas', 'Arkansas', 'ARK', 'SEC'),
('Auburn', 'Auburn', 'AUB', 'SEC'),
('Florida', 'Florida', 'FLA', 'SEC'),
('Georgia', 'Georgia', 'UGA', 'SEC'),
('Kentucky', 'Kentucky', 'UK', 'SEC'),
('LSU', 'LSU', 'LSU', 'SEC'),
('Mississippi State', 'Mississippi State', 'MSST', 'SEC'),
('Missouri', 'Missouri', 'MIZ', 'SEC'),
('Oklahoma', 'Oklahoma', 'OU', 'SEC'),
('Ole Miss', 'Ole Miss', 'MISS', 'SEC'),
('South Carolina', 'South Carolina', 'SC', 'SEC'),
('Tennessee', 'Tennessee', 'TENN', 'SEC'),
('Texas', 'Texas', 'TEX', 'SEC'),
('Texas A&M', 'Texas A&M', 'TAMU', 'SEC'),
('Vanderbilt', 'Vanderbilt', 'VAN', 'SEC'),
('Appalachian State', 'App State', 'APP', 'Sun Belt'),
('Arkansas State', 'Arkansas State', 'ARST', 'Sun Belt'),
('Coastal Carolina', 'Coastal Carolina', 'CCU', 'Sun Belt'),
('Georgia Southern', 'Georgia Southern', 'GASO', 'Sun Belt'),
('Georgia State', 'Georgia State', 'GAST', 'Sun Belt'),
('James Madison', 'James Madison', 'JMU', 'Sun Belt'),
('Louisiana', 'Louisiana', 'UL', 'Sun Belt'),
('Louisiana Tech', 'Louisiana Tech', 'LT', 'Sun Belt'),
('Louisiana-Monroe', 'ULM', 'ULM', 'Sun Belt'),
('Marshall', 'Marshall', 'MRSH', 'Sun Belt'),
('Old Dominion', 'Old Dominion', 'ODU', 'Sun Belt'),
('South Alabama', 'South Alabama', 'USA', 'Sun Belt'),
('Southern Miss', 'Southern Miss', 'USM', 'Sun Belt'),
('Troy', 'Troy', 'TROY', 'Sun Belt'),
('UConn', 'UConn', 'CONN', 'Independent'),
('Notre Dame', 'Notre Dame', 'ND', 'Independent')
on conflict (abbreviation) do update set
  school_name = excluded.school_name,
  short_name = excluded.short_name,
  conference = excluded.conference,
  active = true;

commit;
