create extension if not exists pg_cron;
create extension if not exists pg_net;

create table public.live_scoreboard_dispatches (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique,
  dispatched_at timestamptz not null default clock_timestamp(),
  completed_at timestamptz,
  status text not null default 'pending' check (status in ('pending', 'succeeded', 'failed', 'timed_out')),
  http_status integer,
  error_category text check (error_category in ('timeout', 'network', 'http_4xx', 'http_5xx')),
  constraint live_scoreboard_dispatch_completion_check check (
    (status = 'pending' and completed_at is null and http_status is null and error_category is null)
    or (status <> 'pending' and completed_at is not null)
  )
);

create index live_scoreboard_dispatches_recent_idx
on public.live_scoreboard_dispatches(dispatched_at desc);

alter table public.live_scoreboard_dispatches enable row level security;

create policy "Commissioners can read live dispatcher diagnostics"
on public.live_scoreboard_dispatches for select to authenticated using (
  exists (
    select 1 from public.leagues league
    where league.commissioner_id = (select auth.uid())
  )
);

grant select on public.live_scoreboard_dispatches to authenticated;
revoke insert, update, delete, truncate, references, trigger
on public.live_scoreboard_dispatches from public, anon, authenticated;
revoke all on sequence public.live_scoreboard_dispatches_id_seq from public, anon, authenticated;

create function public.configure_live_scoreboard_dispatch_secret(target_secret text)
returns boolean
language plpgsql security definer set search_path = '' as $$
declare secret_id uuid;
begin
  if length(coalesce(target_secret, '')) < 16 then
    raise exception 'Live scoreboard dispatch secret is invalid' using errcode = '22023';
  end if;

  select id into secret_id
  from vault.secrets
  where name = 'live_scoreboard_dispatch_secret';

  if secret_id is null then
    perform vault.create_secret(
      target_secret,
      'live_scoreboard_dispatch_secret',
      'Bearer credential for the protected production live-scoreboard dispatcher'
    );
  else
    perform vault.update_secret(
      secret_id,
      target_secret,
      'live_scoreboard_dispatch_secret',
      'Bearer credential for the protected production live-scoreboard dispatcher'
    );
  end if;

  return true;
end; $$;

create function private.reconcile_live_scoreboard_dispatches()
returns integer
language plpgsql security definer set search_path = '' as $$
declare updated_count integer;
begin
  update public.live_scoreboard_dispatches dispatch
  set completed_at = response.created,
      status = case
        when response.timed_out then 'timed_out'
        when response.error_msg is not null then 'failed'
        when response.status_code between 200 and 299 then 'succeeded'
        else 'failed'
      end,
      http_status = response.status_code,
      error_category = case
        when response.timed_out then 'timeout'
        when response.error_msg is not null then 'network'
        when response.status_code between 400 and 499 then 'http_4xx'
        when response.status_code >= 500 then 'http_5xx'
      end
  from net._http_response response
  where dispatch.status = 'pending'
    and dispatch.request_id = response.id;

  get diagnostics updated_count = row_count;
  return updated_count;
end; $$;

create function private.dispatch_live_scoreboard_poll()
returns bigint
language plpgsql security definer set search_path = '' as $$
declare
  dispatch_secret text;
  request_identifier bigint;
begin
  perform private.reconcile_live_scoreboard_dispatches();

  select decrypted_secret into dispatch_secret
  from vault.decrypted_secrets
  where name = 'live_scoreboard_dispatch_secret';

  if dispatch_secret is null then
    raise exception 'Live scoreboard dispatch credential is unavailable' using errcode = '55000';
  end if;

  select net.http_get(
    url := 'https://gameheeltigerneerrines.com/api/cron/cfbd-live',
    headers := jsonb_build_object('Authorization', 'Bearer ' || dispatch_secret),
    timeout_milliseconds := 60000
  ) into request_identifier;

  insert into public.live_scoreboard_dispatches(request_id)
  values (request_identifier);

  return request_identifier;
end; $$;

create function private.cleanup_live_scoreboard_dispatch_history()
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare dispatch_rows integer; cron_rows integer;
begin
  perform private.reconcile_live_scoreboard_dispatches();

  delete from public.live_scoreboard_dispatches
  where dispatched_at < clock_timestamp() - interval '14 days';
  get diagnostics dispatch_rows = row_count;

  delete from cron.job_run_details
  where end_time < clock_timestamp() - interval '14 days';
  get diagnostics cron_rows = row_count;

  return jsonb_build_object('dispatch_rows', dispatch_rows, 'cron_rows', cron_rows);
end; $$;

revoke all on function public.configure_live_scoreboard_dispatch_secret(text) from public, anon, authenticated;
grant execute on function public.configure_live_scoreboard_dispatch_secret(text) to service_role;
revoke all on function private.reconcile_live_scoreboard_dispatches() from public, anon, authenticated, service_role;
revoke all on function private.dispatch_live_scoreboard_poll() from public, anon, authenticated, service_role;
revoke all on function private.cleanup_live_scoreboard_dispatch_history() from public, anon, authenticated, service_role;

